quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:cotacoes_db}
quarkus.datasource.username=${POSTGRES_USER:postgres}
quarkus.datasource.password=${POSTGRES_PASSWORD:admin}

quarkus.http.port=8083

quarkus.hibernate-orm.database.generation=update

quarkus.rest-client."org.com.mineradora.client.ClientPriceClient".url=https://economia.awesomeapi.com.br

quarkus.kafka.devservices.enabled=false

mp.messaging.outgoing.quotation-topic.connector=smallrye-kafka
mp.messaging.outgoing.quotation-topic.topic=quotation-topic
kafka.bootstrap.servers=localhost:9092
