
quarkus.http.port=8081

quarkus.arc.fail-on-intercepted-private-method=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:proposal_db}
quarkus.datasource.username=${POSTGRES_USER:postgres}
quarkus.datasource.password=${POSTGRES_PASSWORD:admin}

quarkus.hibernate-orm.database.generation=update

quarkus.oidc.auth-server-url=http://localhost:${8091:8080}/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret

quarkus.kafka.devservices.enabled=false

mp.messaging.outgoing.proposal-topic.connector=smallrye-kafka
mp.messaging.outgoing.proposal-topic.topic=proposal-topic
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.proposal-topic.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer