quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:record_db}
quarkus.datasource.username=${POSTGRES_USER:postgres}
quarkus.datasource.password=${POSTGRES_PASSWORD:admin}

quarkus.hibernate-orm.database.generation=update

quarkus.oidc.auth-server-url=http://localhost:${8091:8080}/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret

mp.messaging.incoming.quotation-topic.connector=smallrye-kafka
mp.messaging.incoming.proposal-topic.connector=smallrye-kafka
mp.messaging.incoming.quotation-topic.topic=quotation-topic
mp.messaging.incoming.proposal-topic.topic=proposal-topic
kafka.bootstrap.servers=localhost:9092