quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:record_db}
quarkus.datasource.username=${POSTGRES_USER:postgres}
quarkus.datasource.password=${POSTGRES_PASSWORD:admin}

quarkus.hibernate-orm.database.generation=update

quarkus.oidc.auth-server-url=http://localhost:8091/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret

quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
quarkus.oidc-client.grant.type=password

quarkus.otel.service-name=relatorio
quarkus.otel.sampler-type=always_on
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-description = BR Mineradora: Trade de Minerio - Back-End For Front-End (BFF) - API


mp.messaging.incoming.quotation-topic.connector=smallrye-kafka
mp.messaging.incoming.proposal-topic.connector=smallrye-kafka
mp.messaging.incoming.quotation-topic.topic=quotation-topic
mp.messaging.incoming.proposal-topic.topic=proposal-topic
kafka.bootstrap.servers=localhost:9092